security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            entry_point: form_login

            # Configuration du formulaire de login
            form_login:
                login_path: app_login       # route de la page de connexion
                check_path: app_login       # route pour soumettre les identifiants
                enable_csrf: true           # activer la protection CSRF pour le login

            # Configuration du logout
            logout:
                path: app_logout            # route de déconnexion
                target: app_home            # redirection après déconnexion

            # Configuration "Remember Me" (souvenez-vous de moi)
            remember_me:
                secret: '%kernel.secret%'   # clé secrète de l'application
                lifetime: 604800            # durée de vie du cookie en secondes (7 jours)
                path: /

    # Contrôle d'accès pour restreindre certaines routes par rôle
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # restreindre l'accès à la route /admin pour les administrateurs
        - { path: ^/profile, roles: ROLE_USER } # restreindre l'accès à la route /profile pour les utilisateurs connectés

